call analysis
metomi/fab pull request #125
Opened 2022-07-08 15:15 UTC by bblay

Automatically identifies symbol dependencies from call statements.
Does not recognise a call on a single-line if statement, of which jules has one.

2022-08-12 08:00 UTC, MatthewHambley requested changes
There is some unit testing of the analyser from data structure but this is definitely a candidate for some system testing from actual source files. This would be part of a wider system testing campaign but if it can be done piece-meal that would allow us to get some value quickly.

2022-08-12 14:14 UTC, bblay commented on run_configs/jules/build_jules.py
> +        # 'conversions_mod', 'water_constants_mod', 'planet_constants_mod', 'veg_param_mod', 'flake_interface'
You mean a _valid_ reason? 😄 It was kept around for fear of losing it, but of course it'll always be in the git history. Will remove.

2022-08-12 14:34 UTC, bblay commented on source/fab/tasks/fortran.py
> +                    analysed_file.add_symbol_dep(called_name.string)
For CALLed dependencies, any standard library calls _do_ get added to the set of symbol dependencies in `AnalysedFile`. However, shortly afterwards `_gen_file_deps` transforms symbol deps into file deps, and tolerates unfound symbols, as is necessary for both standard and third party libraries.

On the USE side of things, `FortranAnalyser._intrinsic_modules` defines modules to ignore, including `iso_fortran_env`.

2022-08-15 08:05 UTC, MatthewHambley approved these changes
This seems okay.

2022-08-15 09:24 UTC, merged