Support full paths in FC
metomi/fab pull request #276
Opened 2023-12-11 01:45 UTC by ScottWales

Allow FC to be a full compiler path

Use LD for the linker in zero-config builds

Fixes #275

2023-12-20 08:35 UTC, MatthewHambley requested changes
This is a good change which tackles a known usage pattern. There is still the issue of compiler executables being versioned, e.g. `myfortran-x.y.z` but that can be left 'till later.

2023-12-20 08:35 UTC, MatthewHambley commented on source/fab/cli.py
> +def cli_fab(folder: Path = None, kwargs: Optional[Dict] = None):
Since you're making this argument optional don't forget to type hint it with `Optional[]`.

2024-01-11 09:15 UTC, james-bruten-mo submitted a review, later dismissed
This looks sensible to me and I can see you've added the Optional label requested by Matthew so I think everything is good

2024-01-11 13:26 UTC, james-bruten-mo commented
Hi Scott, the build tests on the merge are failing with `Argument 1 to "_generic_build_config" has incompatible type "Union[Path, Any, None]"; expected "Path"`. I assume you now only want to call `_generic_build_config` from `cli_fab` when folder is not None. Cheers

2024-01-14 23:11 UTC, ScottWales commented
Fixed up the typing (the `Optional[]` on folder is needed to make the command line entry_point work)

2024-01-15 08:22 UTC, james-bruten-mo approved these changes
Changes now pass unit tests, thanks

2024-01-15 08:22 UTC, merged